// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// LiveTailData currently holds nothing — filters live in URL query
// params parsed by the SSE handler, not server-rendered. The struct
// stays present so future fields (saved-filter dropdowns, etc.) plug
// in without rewiring the handler.
type LiveTailData struct{}

// LiveTail is the operator's real-time event stream view. The page
// opens an EventSource to /live/stream; the JS handles pause/resume
// and a per-connection drop counter reported by the server via a
// "drops" SSE event.
func LiveTail(d LiveTailData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card\"><h2>Live tail</h2><p class=\"muted\">Streams OCSF events from the ingest bus as they arrive. Filters are advisory — they narrow what your tab sees, but other tabs and the ClickHouse writer still receive every event.</p><div id=\"filters\" class=\"live-filters\"><label>host_id <input id=\"filter-host\" type=\"text\" placeholder=\"UUID or substring\"></label> <label>class_uid <input id=\"filter-class\" type=\"text\" placeholder=\"1007 / 1001 / 4001 / 2004\"></label> <label>contains <input id=\"filter-text\" type=\"text\" placeholder=\"raw substring\"></label> <button id=\"apply\" type=\"button\">Apply</button> <button id=\"pause\" type=\"button\">Pause</button></div><div id=\"status\" class=\"muted live-status\">disconnected</div><pre id=\"events\" class=\"live-stream\"></pre><div id=\"footer\" class=\"muted live-footer\">drops: <span id=\"drops\">0</span></div></div><script src=\"/static/livetail.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Live tail").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
