// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AuthAuthCtx struct {
	_       structs.HostLayout
	Service [32]int8
	User    [64]int8
	Rhost   [64]int8
	Tty     [32]int8
}

type AuthAuthEvent struct {
	_       structs.HostLayout
	TsNs    uint64
	Kind    uint32
	Pid     uint32
	Tgid    uint32
	Uid     uint32
	Gid     uint32
	Result  int32
	Pad0    uint32
	Service [32]int8
	User    [64]int8
	Rhost   [64]int8
	Tty     [32]int8
	Comm    [16]int8
	_       [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	AuthMapEvents                    = "events"
	AuthMapPamCtx                    = "pam_ctx"
	AuthProgHandlePamAuthenticateRet = "handle_pam_authenticate_ret"
	AuthProgHandlePamCloseSessionRet = "handle_pam_close_session_ret"
	AuthProgHandlePamEnd             = "handle_pam_end"
	AuthProgHandlePamOpenSessionRet  = "handle_pam_open_session_ret"
	AuthProgHandlePamSetItem         = "handle_pam_set_item"
	AuthProgHandlePamStart           = "handle_pam_start"
	AuthProgHandlePamStartConfdir    = "handle_pam_start_confdir"
	AuthVarUnused                    = "unused"
)

// LoadAuth returns the embedded CollectionSpec for Auth.
func LoadAuth() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AuthBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Auth: %w", err)
	}

	return spec, err
}

// LoadAuthObjects loads Auth and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AuthObjects
//	*AuthPrograms
//	*AuthMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAuthObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAuth()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AuthSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AuthSpecs struct {
	AuthProgramSpecs
	AuthMapSpecs
	AuthVariableSpecs
}

// AuthProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AuthProgramSpecs struct {
	HandlePamAuthenticateRet *ebpf.ProgramSpec `ebpf:"handle_pam_authenticate_ret"`
	HandlePamCloseSessionRet *ebpf.ProgramSpec `ebpf:"handle_pam_close_session_ret"`
	HandlePamEnd             *ebpf.ProgramSpec `ebpf:"handle_pam_end"`
	HandlePamOpenSessionRet  *ebpf.ProgramSpec `ebpf:"handle_pam_open_session_ret"`
	HandlePamSetItem         *ebpf.ProgramSpec `ebpf:"handle_pam_set_item"`
	HandlePamStart           *ebpf.ProgramSpec `ebpf:"handle_pam_start"`
	HandlePamStartConfdir    *ebpf.ProgramSpec `ebpf:"handle_pam_start_confdir"`
}

// AuthMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AuthMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	PamCtx *ebpf.MapSpec `ebpf:"pam_ctx"`
}

// AuthVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AuthVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// AuthObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAuthObjects or ebpf.CollectionSpec.LoadAndAssign.
type AuthObjects struct {
	AuthPrograms
	AuthMaps
	AuthVariables
}

func (o *AuthObjects) Close() error {
	return _AuthClose(
		&o.AuthPrograms,
		&o.AuthMaps,
	)
}

// AuthMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAuthObjects or ebpf.CollectionSpec.LoadAndAssign.
type AuthMaps struct {
	Events *ebpf.Map `ebpf:"events"`
	PamCtx *ebpf.Map `ebpf:"pam_ctx"`
}

func (m *AuthMaps) Close() error {
	return _AuthClose(
		m.Events,
		m.PamCtx,
	)
}

// AuthVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAuthObjects or ebpf.CollectionSpec.LoadAndAssign.
type AuthVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// AuthPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAuthObjects or ebpf.CollectionSpec.LoadAndAssign.
type AuthPrograms struct {
	HandlePamAuthenticateRet *ebpf.Program `ebpf:"handle_pam_authenticate_ret"`
	HandlePamCloseSessionRet *ebpf.Program `ebpf:"handle_pam_close_session_ret"`
	HandlePamEnd             *ebpf.Program `ebpf:"handle_pam_end"`
	HandlePamOpenSessionRet  *ebpf.Program `ebpf:"handle_pam_open_session_ret"`
	HandlePamSetItem         *ebpf.Program `ebpf:"handle_pam_set_item"`
	HandlePamStart           *ebpf.Program `ebpf:"handle_pam_start"`
	HandlePamStartConfdir    *ebpf.Program `ebpf:"handle_pam_start_confdir"`
}

func (p *AuthPrograms) Close() error {
	return _AuthClose(
		p.HandlePamAuthenticateRet,
		p.HandlePamCloseSessionRet,
		p.HandlePamEnd,
		p.HandlePamOpenSessionRet,
		p.HandlePamSetItem,
		p.HandlePamStart,
		p.HandlePamStartConfdir,
	)
}

func _AuthClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed auth_bpfel.o
var _AuthBytes []byte
