// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CgroupCgroupEvent struct {
	_     structs.HostLayout
	TsNs  uint64
	Kind  uint32
	Pid   uint32
	Tgid  uint32
	Uid   uint32
	Gid   uint32
	Root  int32
	Level int32
	Pad0  uint32
	Id    uint64
	Path  [256]int8
	Comm  [16]int8
}

// LoadCgroup returns the embedded CollectionSpec for Cgroup.
func LoadCgroup() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Cgroup: %w", err)
	}

	return spec, err
}

// LoadCgroupObjects loads Cgroup and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CgroupObjects
//	*CgroupPrograms
//	*CgroupMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCgroupObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCgroup()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CgroupSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupSpecs struct {
	CgroupProgramSpecs
	CgroupMapSpecs
	CgroupVariableSpecs
}

// CgroupProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupProgramSpecs struct {
	HandleCgroupMkdir *ebpf.ProgramSpec `ebpf:"handle_cgroup_mkdir"`
	HandleCgroupRmdir *ebpf.ProgramSpec `ebpf:"handle_cgroup_rmdir"`
}

// CgroupMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// CgroupVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// CgroupObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupObjects struct {
	CgroupPrograms
	CgroupMaps
	CgroupVariables
}

func (o *CgroupObjects) Close() error {
	return _CgroupClose(
		&o.CgroupPrograms,
		&o.CgroupMaps,
	)
}

// CgroupMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *CgroupMaps) Close() error {
	return _CgroupClose(
		m.Events,
	)
}

// CgroupVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// CgroupPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupPrograms struct {
	HandleCgroupMkdir *ebpf.Program `ebpf:"handle_cgroup_mkdir"`
	HandleCgroupRmdir *ebpf.Program `ebpf:"handle_cgroup_rmdir"`
}

func (p *CgroupPrograms) Close() error {
	return _CgroupClose(
		p.HandleCgroupMkdir,
		p.HandleCgroupRmdir,
	)
}

func _CgroupClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgroup_bpfel.o
var _CgroupBytes []byte
