// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DnsDnsEvent struct {
	_          structs.HostLayout
	TsNs       uint64
	Kind       uint32
	Pid        uint32
	Tgid       uint32
	Uid        uint32
	Gid        uint32
	Family     uint16
	Sport      uint16
	Dport      uint16
	Pad0       uint16
	PayloadLen uint32
	Saddr      [16]uint8
	Daddr      [16]uint8
	Comm       [16]int8
	Payload    [1024]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	DnsMapEvents            = "events"
	DnsProgHandleIp6SendSkb = "handle_ip6_send_skb"
	DnsProgHandleIpSendSkb  = "handle_ip_send_skb"
	DnsProgHandleSkbRecvUdp = "handle_skb_recv_udp"
	DnsVarUnused            = "unused"
)

// LoadDns returns the embedded CollectionSpec for Dns.
func LoadDns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Dns: %w", err)
	}

	return spec, err
}

// LoadDnsObjects loads Dns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DnsObjects
//	*DnsPrograms
//	*DnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDnsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsSpecs struct {
	DnsProgramSpecs
	DnsMapSpecs
	DnsVariableSpecs
}

// DnsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsProgramSpecs struct {
	HandleIp6SendSkb *ebpf.ProgramSpec `ebpf:"handle_ip6_send_skb"`
	HandleIpSendSkb  *ebpf.ProgramSpec `ebpf:"handle_ip_send_skb"`
	HandleSkbRecvUdp *ebpf.ProgramSpec `ebpf:"handle_skb_recv_udp"`
}

// DnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// DnsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// DnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsObjects struct {
	DnsPrograms
	DnsMaps
	DnsVariables
}

func (o *DnsObjects) Close() error {
	return _DnsClose(
		&o.DnsPrograms,
		&o.DnsMaps,
	)
}

// DnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *DnsMaps) Close() error {
	return _DnsClose(
		m.Events,
	)
}

// DnsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// DnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsPrograms struct {
	HandleIp6SendSkb *ebpf.Program `ebpf:"handle_ip6_send_skb"`
	HandleIpSendSkb  *ebpf.Program `ebpf:"handle_ip_send_skb"`
	HandleSkbRecvUdp *ebpf.Program `ebpf:"handle_skb_recv_udp"`
}

func (p *DnsPrograms) Close() error {
	return _DnsClose(
		p.HandleIp6SendSkb,
		p.HandleIpSendSkb,
		p.HandleSkbRecvUdp,
	)
}

func _DnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dns_bpfel.o
var _DnsBytes []byte
