// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FileFileEvent struct {
	_       structs.HostLayout
	TsNs    uint64
	Kind    uint32
	Pid     uint32
	Tgid    uint32
	Uid     uint32
	Gid     uint32
	Flags   uint32
	Mode    uint32
	Extra   uint32
	Pad     uint32
	Comm    [16]int8
	Path    [256]int8
	Newpath [256]int8
	_       [4]byte
}

// LoadFile returns the embedded CollectionSpec for File.
func LoadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load File: %w", err)
	}

	return spec, err
}

// LoadFileObjects loads File and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileObjects
//	*FilePrograms
//	*FileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileSpecs struct {
	FileProgramSpecs
	FileMapSpecs
	FileVariableSpecs
}

// FileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileProgramSpecs struct {
	HandleSysEnter *ebpf.ProgramSpec `ebpf:"handle_sys_enter"`
}

// FileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// FileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// FileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileObjects struct {
	FilePrograms
	FileMaps
	FileVariables
}

func (o *FileObjects) Close() error {
	return _FileClose(
		&o.FilePrograms,
		&o.FileMaps,
	)
}

// FileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *FileMaps) Close() error {
	return _FileClose(
		m.Events,
	)
}

// FileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// FilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilePrograms struct {
	HandleSysEnter *ebpf.Program `ebpf:"handle_sys_enter"`
}

func (p *FilePrograms) Close() error {
	return _FileClose(
		p.HandleSysEnter,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfel.o
var _FileBytes []byte
