// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type KernelKernelEvent struct {
	_        structs.HostLayout
	TsNs     uint64
	Kind     uint32
	Pid      uint32
	Tgid     uint32
	Uid      uint32
	Gid      uint32
	Result   int32
	Taints   uint32
	AttrType uint32
	Config   uint64
	Config2  uint64
	Name     [64]int8
	Target   [128]int8
	Comm     [16]int8
}

// LoadKernel returns the embedded CollectionSpec for Kernel.
func LoadKernel() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KernelBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Kernel: %w", err)
	}

	return spec, err
}

// LoadKernelObjects loads Kernel and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KernelObjects
//	*KernelPrograms
//	*KernelMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKernelObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKernel()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KernelSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KernelSpecs struct {
	KernelProgramSpecs
	KernelMapSpecs
	KernelVariableSpecs
}

// KernelProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KernelProgramSpecs struct {
	HandleBpf             *ebpf.ProgramSpec `ebpf:"handle_bpf"`
	HandleFinitModuleExit *ebpf.ProgramSpec `ebpf:"handle_finit_module_exit"`
	HandleInitModuleExit  *ebpf.ProgramSpec `ebpf:"handle_init_module_exit"`
	HandleModuleFree      *ebpf.ProgramSpec `ebpf:"handle_module_free"`
	HandleModuleLoad      *ebpf.ProgramSpec `ebpf:"handle_module_load"`
	HandlePerfEventOpen   *ebpf.ProgramSpec `ebpf:"handle_perf_event_open"`
}

// KernelMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KernelMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// KernelVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KernelVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// KernelObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type KernelObjects struct {
	KernelPrograms
	KernelMaps
	KernelVariables
}

func (o *KernelObjects) Close() error {
	return _KernelClose(
		&o.KernelPrograms,
		&o.KernelMaps,
	)
}

// KernelMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type KernelMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *KernelMaps) Close() error {
	return _KernelClose(
		m.Events,
	)
}

// KernelVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type KernelVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// KernelPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type KernelPrograms struct {
	HandleBpf             *ebpf.Program `ebpf:"handle_bpf"`
	HandleFinitModuleExit *ebpf.Program `ebpf:"handle_finit_module_exit"`
	HandleInitModuleExit  *ebpf.Program `ebpf:"handle_init_module_exit"`
	HandleModuleFree      *ebpf.Program `ebpf:"handle_module_free"`
	HandleModuleLoad      *ebpf.Program `ebpf:"handle_module_load"`
	HandlePerfEventOpen   *ebpf.Program `ebpf:"handle_perf_event_open"`
}

func (p *KernelPrograms) Close() error {
	return _KernelClose(
		p.HandleBpf,
		p.HandleFinitModuleExit,
		p.HandleInitModuleExit,
		p.HandleModuleFree,
		p.HandleModuleLoad,
		p.HandlePerfEventOpen,
	)
}

func _KernelClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kernel_bpfel.o
var _KernelBytes []byte
