// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetNetEvent struct {
	_      structs.HostLayout
	TsNs   uint64
	Kind   uint32
	Pid    uint32
	Tgid   uint32
	Uid    uint32
	Gid    uint32
	Family uint16
	Proto  uint8
	Pad0   uint8
	Sport  uint16
	Dport  uint16
	Saddr  [16]uint8
	Daddr  [16]uint8
	Comm   [16]int8
	_      [4]byte
}

// LoadNet returns the embedded CollectionSpec for Net.
func LoadNet() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Net: %w", err)
	}

	return spec, err
}

// LoadNetObjects loads Net and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetObjects
//	*NetPrograms
//	*NetMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNet()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetSpecs struct {
	NetProgramSpecs
	NetMapSpecs
	NetVariableSpecs
}

// NetProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetProgramSpecs struct {
	HandleInetCskAccept *ebpf.ProgramSpec `ebpf:"handle_inet_csk_accept"`
	HandleTcpConnect    *ebpf.ProgramSpec `ebpf:"handle_tcp_connect"`
	HandleUdpSendmsg    *ebpf.ProgramSpec `ebpf:"handle_udp_sendmsg"`
}

// NetMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// NetVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// NetObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetObjects struct {
	NetPrograms
	NetMaps
	NetVariables
}

func (o *NetObjects) Close() error {
	return _NetClose(
		&o.NetPrograms,
		&o.NetMaps,
	)
}

// NetMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *NetMaps) Close() error {
	return _NetClose(
		m.Events,
	)
}

// NetVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// NetPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetPrograms struct {
	HandleInetCskAccept *ebpf.Program `ebpf:"handle_inet_csk_accept"`
	HandleTcpConnect    *ebpf.Program `ebpf:"handle_tcp_connect"`
	HandleUdpSendmsg    *ebpf.Program `ebpf:"handle_udp_sendmsg"`
}

func (p *NetPrograms) Close() error {
	return _NetClose(
		p.HandleInetCskAccept,
		p.HandleTcpConnect,
		p.HandleUdpSendmsg,
	)
}

func _NetClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed net_bpfel.o
var _NetBytes []byte
