// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ProcessProcessEvent struct {
	_          structs.HostLayout
	TsNs       uint64
	Kind       uint32
	Pid        uint32
	Tgid       uint32
	Ppid       uint32
	Uid        uint32
	Gid        uint32
	ExitCode   int32
	CmdlineLen uint32
	Comm       [16]int8
	Exe        [128]int8
	Cmdline    [256]int8
}

// LoadProcess returns the embedded CollectionSpec for Process.
func LoadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Process: %w", err)
	}

	return spec, err
}

// LoadProcessObjects loads Process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessObjects
//	*ProcessPrograms
//	*ProcessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessSpecs struct {
	ProcessProgramSpecs
	ProcessMapSpecs
	ProcessVariableSpecs
}

// ProcessProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessProgramSpecs struct {
	HandleExec *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork *ebpf.ProgramSpec `ebpf:"handle_fork"`
}

// ProcessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ProcessVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// ProcessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessObjects struct {
	ProcessPrograms
	ProcessMaps
	ProcessVariables
}

func (o *ProcessObjects) Close() error {
	return _ProcessClose(
		&o.ProcessPrograms,
		&o.ProcessMaps,
	)
}

// ProcessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ProcessMaps) Close() error {
	return _ProcessClose(
		m.Events,
	)
}

// ProcessVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// ProcessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessPrograms struct {
	HandleExec *ebpf.Program `ebpf:"handle_exec"`
	HandleExit *ebpf.Program `ebpf:"handle_exit"`
	HandleFork *ebpf.Program `ebpf:"handle_fork"`
}

func (p *ProcessPrograms) Close() error {
	return _ProcessClose(
		p.HandleExec,
		p.HandleExit,
		p.HandleFork,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfel.o
var _ProcessBytes []byte
